---
user:
    id: decrement
    first_name: first_name
    last_name: last_name
    email: email
    score: int
    created_at: [date, "between(2010:2020)","min(10)"]
temperature:
    index: increment
    temp_c: [float,"between(1,2)","prefix(c,f)"]
